In [1]:
import numpy as np

In [7]:
#input the resourse matrix
res = ([1,1,0,0,0], [1,1,1,1,0], [0,0,0,2,3])
price = ([1,2,3,5,8])
demand = ([6,2,1])

In [11]:
#part b
q = np.dot(res, price)
q

array([ 3, 11, 34])

In [12]:
#part c
np.dot(demand, res)

array([8, 8, 2, 4, 3])

In [14]:
#part d
np.dot(demand, q)

74

In [2]:
U = ([1,1,0,0,0], [3,3,0,0,0]
          )

In [3]:
U


([1, 1, 0, 0, 0], [3, 3, 0, 0, 0])

In [4]:
UT = np.transpose(U)

In [5]:
UT


array([[1, 3],
       [1, 3],
       [0, 0],
       [0, 0],
       [0, 0]])

In [8]:
x = ([3], [-1])

In [9]:
np.dot(UT, x)

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [10]:
U = ([1,2], [2,-1],[-3,2]        )

In [13]:
U

([1, 2], [2, -1], [-3, 2])

In [ ]:
y =[0,1,-1]