In [1]:
import numpy as np
import sympy

In [2]:
x = np.array([[2,1],  [3.1,1.4], [4.5, 2.5], [5, 2.7]])
x

array([[2. , 1. ],
       [3.1, 1.4],
       [4.5, 2.5],
       [5. , 2.7]])

In [7]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(x.T)

In [8]:
principalComponents


array([[ 1.81521349],
       [-1.81521349]])

In [3]:
def GramSchmidt(Xr):
    ulist = []
    x1 = Xr[:,[0]]
    dx1 = np.linalg.norm(x1)
    u1 = x1 / dx1
    ulist.append(u1)
    for i in range(1, Xr.shape[1]):
        xi = Xr[:,[i]]
        for u in ulist:
            w = np.dot(np.transpose(u), xi)
            xi = xi - w*u
        dxi = np.linalg.norm(xi)
        ui = xi / dxi
        ulist.append(ui)
        u1 = np.concatenate(((u1, ui)), axis = 1)
        U = u1[:,~np.all(np.isnan(u1), axis=0)]
    print('The rank of X is %d' %U.shape[1])
    return U

In [4]:
GramSchmidt(x)

The rank of X is 2


array([[ 0.2606873 , -0.20172483],
       [ 0.40406531, -0.84912788],
       [ 0.58654642,  0.44020977],
       [ 0.65171824,  0.21096043]])

In [8]:
test = np.array([[1,1],  [1,3], [0,0]])
test

array([[1, 1],
       [1, 3],
       [0, 0]])

In [9]:
GramSchmidt(test)

The rank of X is 2


array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678],
       [ 0.        ,  0.        ]])

In [10]:
b= np.array([[3,1,2,1],  [0,3,6,0], [0,4,8,0]])

In [11]:
GramSchmidt(b)

The rank of X is 2


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]


array([[1. , 0. ],
       [0. , 0.6],
       [0. , 0.8]])